--15
select count(*) SOTP 
from tacpham;
--16
SELECT T.nt,TUA, COUNT(*) SOSACH
FROM TACPHAM T JOIN SACH S ON T.NT=S.NT
GROUP BY T.NT, TUA
ORDER BY T.NT;
--17
SELECT T.nt,TUA, COUNT(*) SOSACH
FROM TACPHAM T JOIN SACH S ON T.NT=S.NT
GROUP BY T.NT, TUA HAVING COUNT(*)>=2
ORDER BY T.NT;
--18
SELECT TACGIA, COUNT(*) SOTP
FROM TACPHAM
GROUP BY TACGIA;
--19
SELECT COUNT(*)
FROM (SELECT TACGIA, COUNT(*) SOTP
        FROM TACPHAM
        GROUP BY TACGIA HAVING COUNT(*) >1);
--20
SELECT nd, EXTRACT(YEAR FROM NGAYMUON) NAM, COUNT(*) SOLANMUON
FROM MUON
GROUP BY ND, EXTRACT(YEAR FROM NGAYMUON)
ORDER BY ND;
--22
CREATE TABLE C22 AS 
    SELECT T.nt,TUA, COUNT(*) SOSACH
    FROM TACPHAM T JOIN SACH S ON T.NT=S.NT
    GROUP BY T.NT, TUA HAVING COUNT(*)>=2
    ORDER BY T.NT;
SELECT *
FROM C22
WHERE SOSACH=(SELECT MAX(SOSACH) FROM C22);
DROP TABLE C22;


SELECT T.nt,TUA, COUNT(*) SOSACH
    FROM TACPHAM T JOIN SACH S ON T.NT=S.NT
    GROUP BY T.NT, TUA HAVING COUNT(*)= (SELECT MAX(COUNT(*)) FROM SACH GROUP BY NT)
    ORDER BY T.NT;
--28
SELECT TUA
FROM TACPHAM T JOIN SACH S ON T.NT=S.NT  LEFT JOIN MUON M ON S.NS=M.NS
WHERE NGAYMUON IS NULL
ORDER BY T.NT
--29
SELECT TUA FROM TACPHAM 
MINUS
SELECT TUA
FROM TACPHAM T JOIN SACH S ON T.NT=S.NT  LEFT JOIN MUON M ON S.NS=M.NS
WHERE NGAYMUON IS NULL