SELECT *
FROM KHOAHOC;
SELECT *
FROM HOCVIEN;
--2
SELECT *
FROM HOCVIEN
WHERE GIOITINH=1;
--3
SELECT *
FROM HOCVIEN
WHERE DIACHI like '%C¿n Tho%';
--4
SELECT l.*
FROM KHOAHOC K, LOP L
WHERE K.MAKH=L.MAKH AND TENKH='Khóa 1';

--4
SELECT l.*
FROM KHOAHOC K JOIN  LOP L ON K.MAKH=L.MAKH  
WHERE TENKH='Khóa 1';

--5
SELECT H.MAHV, TENHV
FROM KHOAHOC K JOIN LOP L ON K.MAKH=L.MAKH 
        JOIN PHIEUTHU P ON P.MALOP=L.MALOP
        JOIN HOCVIEN H ON H.MAHV=P.MAHV
WHERE TENKH='Khóa 1';
--6
--7
SELECT *
FROM HOCVIEN
WHERE EXTRACT(YEAR FROM NGAYSINH)=2002; -- MONTH/DAY
--11
SELECT H.MAHV, TENHV
FROM LOAILOP LL  JOIN LOP L ON LL.MALOAI=L.MALOAI 
        JOIN PHIEUTHU P ON P.MALOP=L.MALOP
        JOIN HOCVIEN H ON H.MAHV=P.MAHV
WHERE TEnLOP='L?p 1' and lower(tenloai)='ti?ng anh c?n b?n';
--15
select count(*) SOHV
from hocvien;
--16
SELECT count(*) sohvlop1
FROM LOAILOP LL  JOIN LOP L ON LL.MALOAI=L.MALOAI 
        JOIN PHIEUTHU P ON P.MALOP=L.MALOP
        JOIN HOCVIEN H ON H.MAHV=P.MAHV
WHERE TEnLOP='L?p 1' and lower(tenloai)='ti?ng anh c?n b?n';